### ISSUE TITLE
Mercurial 4.4: AttributeError: 'module' object has no attribute 'getlocalchangegroup'

### ISSUE THREAD

**Issue by alexbarton** [mnauw/git-remote-hg#9]
Starting with Mercurial 4.4, I get the following error when trying to push to a repository:
```
$ git push
searching for changes
no changes found
searching for changes
Traceback (most recent call last):
  File "/usr/local/bin/git-remote-hg", line 1763, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/git-remote-hg", line 1748, in main
    do_push(parser)
  File "/usr/local/bin/git-remote-hg", line 1526, in do_push
    do_push_refspec(parser, line.lstrip('push '), localrevs)
  File "/usr/local/bin/git-remote-hg", line 1453, in do_push_refspec
    ok = do_push_hg(nparser)
  File "/usr/local/bin/git-remote-hg", line 1329, in do_push_hg
    ret = push(parser.repo, peer, p_revs, force_push)
  File "/usr/local/bin/git-remote-hg", line 1215, in push
    ret = push_unsafe(repo, remote, p_revs, force)
  File "/usr/local/bin/git-remote-hg", line 1178, in push_unsafe
    cg = changegroup.getlocalchangegroup(repo, 'push', outgoing)
AttributeError: 'module' object has no attribute 'getlocalchangegroup'
To hg::ssh://user@fqdn//path/to/repository
   fffffffff..5f36207a3  master -> master
error: failed to push some refs to 'hg::ssh://user@fqdn//path/to/repository'
$ git --version                                                                                                                  ❌ 1 ↵
git version 2.15.0
$ hg --version
Mercurial Distributed SCM (version 4.4)
(see https://mercurial-scm.org for more information)

Copyright (C) 2005-2017 Matt Mackall and others
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
$ sw_vers
ProductName:   Mac OS X
ProductVersion: 10.12.6
BuildVersion:   16G29
$  
```

It worked with Mercurial 4.3.3 (and downgrading helped, for now):
```
$ git push
searching for changes
no changes found
searching for changes
remote: adding changesets
remote: adding manifests
remote: adding file changes
remote: added 1 changesets with 2 changes to 2 files
To hg::ssh://user@fqdn//path/to/repository
   fffffffff..5f36207a3  master -> master$ hg --version
Mercurial Distributed SCM (version 4.3.3)
(see https://mercurial-scm.org for more information)

Copyright (C) 2005-2017 Matt Mackall and others
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
$
```

Please let me know if I can help with something!
